server:
  port: 0

spring:
  application:
    name: auth-service
  rabbitmq:
    host: localhost
    port: 5672
    password: guest
    username: guest

jwt:
  secret: BvPHGM8C0ia4u0uxxqPD5DTbWC9F9TWvPStp3pb7ARo0oK2mJ3pd3YG4lxA9i8bj6OTbadwezxgeEByY
  expiration: 86400


