spring:
  application:
    name: "api-gateway"
  cloud:
    gateway:
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials, RETAIN_UNIQUE
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "http://127.0.0.1:5500/"
            allowedHeaders: "*"
            allowedMethods: "*"
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true

server:
  port: 8082

eureka:
  client:
    service-url:
      defaultZone : http://localhost:8761/eureka

#logging:
#  level:
#    root: INFO
#    org:
#      springframework:
#        cloud:
#          gateway: TRACE
#            route:
#              RouteDefinitionLocator: INFO
#          gateway: